Repository AY2324S2-CS2103T-T10-1/tp, pull requests merged in 2024-03, with the labels that each got.

#121 Update Developer Guide to include use cases for copying email addresses v1.1
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#123 Update developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#125 Update Developer Guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#119 docs: update ui mockup of app.
  docs/images/Ui.png
Labels: type.Task, priority.High

#126 Update formatting of developer guide
  docs/DeveloperGuide.md
Labels: priority.Medium

#129 Improve explaination for prefixes and find command in User Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#132 fix: remove traces of AB3, replace with avengers assemble (AA)
  build.gradle
  docs/UserGuide.md
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/data/JsonUserPrefsStorageTest/TypicalUserPref.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
Labels: type.Task, priority.High

#137 fix: edit typo and formatting error in developer guide
  docs/DeveloperGuide.md
Labels: type.Bug, priority.Medium

#136 fix: change unique parameter of persons in the addressbook to email
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
Labels: type.Task, priority.High

#135 feat: add matriculation number param
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/matric/Matric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/matric/MatricTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#130 Modify functionality of "find" command
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentMultiMapTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/person/PersonDetailContainsKeywordPredicateTest.java
Labels: type.Task, priority.High

#148 docs: add parameter specifications to user guide.
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#142 feat: add export feature to export data in json file to a csv file
  build.gradle
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/data/JsonAddressBookStorageTest/invalidJsonStructureAddressBook.json
  src/test/data/JsonAddressBookStorageTest/noPersonsArrayAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/emptyPersonAddressBook.json
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#144 Add Studio parameter
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/student/Matric.java
  src/main/java/seedu/address/model/student/Studio.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/student/MatricTest.java
  src/test/java/seedu/address/model/student/StudioTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#152 fix: remove test case that is not required for ExportCommand
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: priority.High

#151 Add Reflection parameter
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/student/Reflection.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/data/addressbookdata/addressbooktest.csv
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/student/ReflectionTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#157 Update Model diagram
  .gitignore
  build.gradle
  docs/diagrams/ModelClassDiagram.puml
Labels: type.Task, priority.High

#155 feat: update UML sequence diagram in developer guide to show sequence for export command
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
Labels: type.Task, priority.High

#158 docs: create a sequence diagram for the `add` command.
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/index.md
Labels: type.Task, priority.High

#170 Import command message_usage editted
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: type.Task, priority.High

#173 Fix: Help menu links to the wrong user guide
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: type.Bug, priority.High

#182 Change empty matric display to display nothing
  src/main/java/seedu/address/model/student/Matric.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/model/student/MatricTest.java
Labels: type.Task, priority.Medium

#184 Fix: Save file loads properly when persons have empty optional parameters
  src/main/java/seedu/address/model/student/Matric.java
  src/main/java/seedu/address/model/student/Reflection.java
  src/main/java/seedu/address/model/student/Studio.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
Labels: type.Bug, priority.High

#183 feat: update export feature to export the listed or filtered person
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/test/data/ExportCommandTest/invalidJsonFile.json
  src/test/data/JsonAddressBookStorageTest/noPersonsArrayAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/emptyPersonAddressBook.json
  src/test/data/addressbookdata/addressbooktest.csv
  src/test/java/seedu/address/logic/commands/ExportCommandTest.java
Labels: type.Task, priority.High

#188 Update MainApp to reflect correct version number
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#191 docs: update user guide formatting to improve readability
  docs/UserGuide.md
Labels: priority.Medium

#209 Docs: Edit the UG introduction to better fit the app and remove the "Archiving" section #208
  docs/UserGuide.md
Labels: type.Task, priority.High

#203 Implement Exam Commands
  src/main/java/seedu/address/commons/core/GuiSettings.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/AddExamCommand.java
  src/main/java/seedu/address/logic/commands/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditExamCommand.java
  src/main/java/seedu/address/logic/commands/SelectExamCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddExamCommandParser.java
  src/main/java/seedu/address/logic/parser/AddScoreCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/DeleteExamCommandParser.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/EditExamCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SelectExamCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/exam/UniqueExamList.java
  src/main/java/seedu/address/model/exam/exceptions/DuplicateExamException.java
  src/main/java/seedu/address/model/exam/exceptions/ExamNotFoundException.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Score.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/ExamCard.java
  src/main/java/seedu/address/ui/ExamListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/ExamListCard.fxml
  src/main/resources/view/ExamListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/PersonListCard.fxml
  src/test/data/ExportCommandTest/addressbookdata/addressbooktest.csv
  src/test/data/ExportCommandTest/filteredAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: type.Task, priority.High, severity.High

#200 Update sequence diagrams and Add import implementation in Developer guide
  docs/DeveloperGuide.md
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/ImportSequenceDiagramRef.puml
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
Labels: type.Task, priority.High

#235 Docs: update user guide according to Dr Wee's comments
  docs/UserGuide.md
Labels: type.Task, priority.High

#238 Docs: Update Developer Guide to include documentation for the copy command
  docs/DeveloperGuide.md
  docs/diagrams/CopyImplementationActivityDiagram.puml
Labels: type.Task, priority.High

#247 docs: update developer guide to include implementation for the export feature
  docs/DeveloperGuide.md
  docs/diagrams/ExportSequenceDiagram.puml
Labels: type.Task, priority.High

#202 Build: Enable Assertions
  build.gradle
Labels: type.Task, priority.High

#207 Feat: Improve find command to search with the new optional parameters (matric, reflection & studio)
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonDetailContainsKeywordPredicateTest.java
Labels: type.Task, priority.High

#206 Add CsvUtil class
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: type.Task, priority.High

#199 Feat: delete shown
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteShownCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/commands/DeleteShownCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#218 Add saving of exam scores
  src/main/java/seedu/address/logic/commands/ExportCommand.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/storage/JsonAdaptedExamScore.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Task, priority.High

#243 Implement storage of exams
  src/main/java/seedu/address/storage/JsonAdaptedExam.java
  src/main/java/seedu/address/storage/JsonAdaptedExamScore.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.High

#252 Change SelectExamCommand to use index instead of names
  src/main/java/seedu/address/logic/commands/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/ImportExamCommand.java
  src/main/java/seedu/address/logic/commands/SelectExamCommand.java
  src/main/java/seedu/address/logic/parser/SelectExamCommandParser.java
  src/test/java/seedu/address/logic/commands/AddScoreCommandTest.java
  src/test/java/seedu/address/logic/commands/SelectExamCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/SelectExamCommandParserTest.java
Labels: type.Task, priority.High, severity.Medium

#255 Feat: Update to UI
  src/main/java/seedu/address/ui/ExamCard.java
  src/main/java/seedu/address/ui/ExamListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
Labels: type.Task, priority.High, severity.Medium

#264 feat: add deleteScore command feature
  src/main/java/seedu/address/logic/commands/DeleteScoreCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteScoreCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteScoreCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteScoreCommandParserTest.java
Labels: type.Task, priority.High

#261 feat: add editScore command feature
  src/main/java/seedu/address/logic/commands/EditScoreCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditScoreCommandParser.java
  src/test/java/seedu/address/logic/commands/EditScoreCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditScoreCommandParserTest.java
Labels: type.Task, priority.High

#277 Bug fix: Reflection and Studio must match exact user input in find
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordPredicate.java
  src/test/java/seedu/address/commons/util/StringUtilTest.java
Labels: type.Task, type.Bug, priority.High

#273 Add Statistics for scores of selected exam
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ScoreStatistics.java
  src/main/java/seedu/address/model/person/Score.java
  src/main/java/seedu/address/ui/ExamCard.java
  src/main/java/seedu/address/ui/ExamListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/StatusBarFooter.fxml
  src/test/java/seedu/address/logic/util/ModelStub.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/ScoreStatisticsTest.java
Labels: type.Enhancement, priority.Medium, severity.Low

#280 Branch update user guide statistics
  docs/UserGuide.md
  docs/images/success_images/addScore_success.png
  docs/images/success_images/deleteExam_success.png
  docs/images/success_images/deleteScore_success.png
  docs/images/success_images/editScore_success.png
  docs/images/success_images/mean_median_success.png
  docs/images/success_images/selectExam_success.png
Labels: type.Task, priority.High

#286 feat: update export command to export exam name and scores to csv
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Task, priority.High

#288 Improve slap of Find Command and relevant files
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordAndExamPredicate.java
Labels: type.Task, priority.Medium

#287 Update Spacing in UI and printing of persons
  src/main/java/seedu/address/logic/Messages.java
  src/main/resources/view/ExamListCard.fxml
Labels: type.Bug, priority.High

#289 docs: update formatting of user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#281 Change Score to accept double
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/person/Score.java
  src/main/java/seedu/address/storage/JsonAdaptedExam.java
  src/main/java/seedu/address/storage/JsonAdaptedExamScore.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/java/seedu/address/logic/parser/AddExamCommandParserTest.java
  src/test/java/seedu/address/model/exam/ExamTest.java
  src/test/java/seedu/address/model/person/ScoreTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.High, severity.Medium

#294 fix: edit ui size in user guide to make it visible
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#295 fix: typo in user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#298 Update success images with bigger annotations
  docs/images/success_images/addScore_success.png
  docs/images/success_images/deleteExam_success.png
  docs/images/success_images/deleteScore_success.png
  docs/images/success_images/editScore_success.png
  docs/images/success_images/mean_median_success.png
Labels: type.Task, priority.High
