Repository AY2324S2-CS2103T-T10-1/tp, pull requests merged in 2024-04, with the labels that each got.

#305 Modify AddCommand to throw more specfic exceptions
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/person/Score.java
  src/main/java/seedu/address/storage/JsonAdaptedExam.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedExamTest.java
Labels: type.Task, priority.High

#307 Fix: Rename deleteShown
  src/main/java/seedu/address/logic/commands/DeleteShownCommand.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Task, priority.High

#304 Change special character to pipe symbol "|" for all prefixes and commands
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordAndExamPredicate.java
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordPredicate.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonDetailContainsKeywordAndExamPredicateTest.java
Labels: type.Task, priority.High

#310 Update name of boolean methods
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/test/java/seedu/address/logic/parser/ArgumentMultiMapTest.java
Labels: type.Task, priority.High

#301 Decrease overzealous autotag
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AutomaticTaggingActivityDiagram.puml
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: type.Task, priority.High

#309 Bug fix: Ensure correct naming for Boolean methods in find functionality
  src/main/java/seedu/address/model/person/PersonDetailContainsKeywordAndExamPredicate.java
Labels: type.Task, priority.High

#300 Fix: explicitly enforce email to be the first value of csv file
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/DeleteScoreCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java
  src/main/java/seedu/address/logic/commands/SelectExamCommand.java
  src/main/java/seedu/address/logic/parser/ImportExamScoresCommandParser.java
  src/test/data/ImportExamCommandTest/wrong_headers.csv
  src/test/java/seedu/address/logic/commands/ImportExamScoresCommandTest.java
  src/test/java/seedu/address/logic/parser/ImportExamScoresCommandParserTest.java
Labels: type.Task, priority.High

#302 Feat: limit field length
  docs/UserGuide.md
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/java/seedu/address/model/person/Score.java
  src/main/java/seedu/address/model/student/Reflection.java
  src/main/java/seedu/address/model/student/Studio.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ExamListCard.fxml
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/ImportExamScoresCommandTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: type.Task, priority.High

#314 Fix: typos in success messages
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DeleteExamCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java
  src/main/java/seedu/address/logic/commands/SelectExamCommand.java
  src/test/java/seedu/address/logic/commands/ImportCommandTest.java
Labels: type.Task, priority.High

#312 Limit Mean and Median to show 2DP
  src/main/java/seedu/address/model/ScoreStatistics.java
  src/test/java/seedu/address/model/ScoreStatisticsTest.java
Labels: type.Bug, priority.High

#316 docs: edit user guide and site layout
  docs/UserGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.High

#313 Update UI Images for v1.3
  docs/UserGuide.md
  docs/images/success_images/Ui.png
  docs/images/success_images/addExam_success.png
  docs/images/success_images/addScore_success.png
  docs/images/success_images/add_success.png
  docs/images/success_images/clear_success.png
  docs/images/success_images/copy_success.png
  docs/images/success_images/deleteExam_success.png
  docs/images/success_images/deleteScore_success.png
  docs/images/success_images/deleteShown_success.png
  docs/images/success_images/delete_success.png
  docs/images/success_images/deselectExam_success.png
  docs/images/success_images/editScore_success.png
  docs/images/success_images/edit_success.png
  docs/images/success_images/export_success.png
  docs/images/success_images/find_success.png
  docs/images/success_images/importExam_success.png
  docs/images/success_images/import_success.png
  docs/images/success_images/list_success.png
  docs/images/success_images/mean_median_success.png
  docs/images/success_images/selectExam_success.png
Labels: type.Task, priority.High

#317 Fix: remove pop up window for help command
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/test/java/seedu/address/logic/commands/HelpCommandTest.java
Labels: type.Task, priority.High

#321 Update UG for help command
  docs/UserGuide.md
  docs/images/success_images/helpMessage.png
  docs/images/success_images/help_success.png
Labels: type.Bug

#322 Build: update version number
  src/main/java/seedu/address/MainApp.java
Labels: type.Task, priority.High

#323 fix: add page breaks to ensure good formatting of printed user guide
  docs/UserGuide.md
Labels: priority.Medium

#324 fix: typo in user guide
  docs/UserGuide.md
Labels: priority.Medium

#381 fix: Additional PE-D UG improvements
  docs/UserGuide.md
Labels: type.Task, priority.High

#379 fix: Clarify email and copy related docs and messages
  docs/UserGuide.md
  src/main/java/seedu/address/model/person/Email.java
Labels: type.Task, priority.Medium

#378 Bug fixes for PE-D
  src/main/java/seedu/address/logic/commands/AddExamCommand.java
  src/main/java/seedu/address/logic/commands/AddScoreCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/ui/ExamListPanel.java
  src/main/java/seedu/address/ui/NoSelectionModel.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: type.Bug, priority.High

#382 Fix ped bugs: Leng Khai
  src/main/java/seedu/address/logic/commands/ImportExamScoresCommand.java
  src/main/java/seedu/address/model/exam/Exam.java
  src/main/java/seedu/address/model/person/Name.java
  src/test/java/seedu/address/logic/commands/ImportExamScoresCommandTest.java
Labels: type.Task, type.Bug, priority.High

#330 Bug fix: Refactor Find Functionality
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/ExamPredicate.java
  src/main/java/seedu/address/model/person/PersonDetailPredicate.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteShownCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/ExamPredicateTest.java
  src/test/java/seedu/address/model/person/PersonDetailPredicateTest.java
Labels: type.Bug, priority.High

#390 docs: update DG to reflect user stories and use cases to reflect all implemented functions
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#393 bug fix: prevent execution of find command with duplicated prefixes present
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
Labels: type.Bug, priority.High

#388 Docs: Add assigned parts to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddCommandParsing.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/AutomaticTaggingActivityDiagram.puml
  docs/diagrams/CopyImplementationActivityDiagram.puml
  docs/diagrams/DeleteShownActivityDiagram.puml
  docs/diagrams/EditCommandActivityDiagram.puml
  docs/diagrams/FindImplementationActivityDiagram.puml
  docs/diagrams/ImportExamScoresFileActivityDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/parser/ImportExamScoresCommandParser.java
  src/test/java/seedu/address/logic/parser/ImportExamScoresCommandParserTest.java
Labels: type.Task, priority.High

#392 Docs: Update Manual Testing Section of DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#385 BugFix: Bug Fixes from PED
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/logic/commands/ImportCommand.java
  src/main/java/seedu/address/logic/parser/ImportCommandParser.java
  src/test/data/ImportCommandTest/duplicateHeaders.csv
  src/test/data/ImportCommandTest/empty.csv
  src/test/java/seedu/address/commons/util/CsvUtilTest.java
Labels: type.Bug, priority.High

#387 Add exams and statistics implementations to DG
  docs/DeveloperGuide.md
  docs/diagrams/AddExamExecutionSequenceDiagram.puml
  docs/diagrams/AddExamParsingSequenceDiagram.puml
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/SelectExamSequenceDiagram.puml
  docs/diagrams/StatisticsSequenceDiagram.puml
  src/main/java/seedu/address/model/ModelManager.java
Labels: type.Task, priority.High

#394 docs: update developer guide
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
Labels: type.Task, priority.High

#399 Format implementation section of DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#397 Docs: Update Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/ImportParserSequenceDiagram.puml
  docs/diagrams/ImportSequenceDiagram.puml
  docs/diagrams/ImportSequenceDiagramRef.puml
  src/main/java/seedu/address/logic/commands/ImportCommand.java
Labels: type.Task, priority.High

#398 Docs: Update Command Summary Table
  docs/UserGuide.md
Labels: type.Task, priority.High

#402 docs: Update find implementation in the DG
  docs/DeveloperGuide.md
  docs/diagrams/FindImplementationActivityDiagram.puml
  docs/diagrams/FindImplementationFindByScoreActivityDiagram.puml
  docs/diagrams/FindImplementationPredicateCreationSequenceDiagram.puml
  docs/diagrams/FindImplementationSequenceDiagram.puml
Labels: type.Task, priority.High

#403 docs: update user guide known issues section
  docs/UserGuide.md
Labels: type.Task, priority.High

#406 Enhance UI Outline in UserGuide.md
  docs/UserGuide.md
  docs/images/UiOutline.png
Labels: type.Task, priority.High

#400 docs: update implementation details in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/AddScoreExecutionSequenceDiagram.puml
  docs/diagrams/AddScoreParsingSequenceDiagram.puml
  docs/diagrams/DeleteScoreExecutionSequenceDiagram.puml
  docs/diagrams/DeleteScoreParsingSequenceDiagram.puml
  docs/diagrams/ExportDataRetrievalSequenceDiagram.puml
  docs/diagrams/ExportSequenceDiagram.puml
  docs/diagrams/style.puml
  src/main/java/seedu/address/logic/commands/ExportCommand.java
Labels: type.Task, priority.High

#411 docs: fix minor formatting issues in user guide
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#404 fix: Update DG formatting and site structure
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/_markbind/layouts/default.md
  docs/diagrams/AddExamExecutionSequenceDiagram.puml
  docs/diagrams/StatisticsSequenceDiagram.puml
  docs/diagrams/StorageLoadSequenceDiagram.puml
  docs/index.md
  docs/site.json
Labels: type.Task, priority.High

#412 Edit page breaks in UG
  docs/UserGuide.md
Labels: type.Task, priority.Medium

#417 Reformat Manual Testing Section in DG to follow standard formatting
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: type.Task, priority.High

#416 Reformat Manual Testing Section in DG to follow standard formatting
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#414 Reformat Manual Testing Section in DG to follow standard formatting
  docs/DeveloperGuide.md
Labels: type.Task, priority.High

#418 Update Readme
  README.md
Labels: priority.High

#423 fix: typo in developer guide
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#422 Small changes to manual testing
  docs/DeveloperGuide.md
Labels: type.Task, priority.Medium

#432 Minor Change to DG
  docs/DeveloperGuide.md
Labels: type.Task, priority.Low
